#![deny(clippy::all, clippy::pedantic, clippy::nursery)]
#![allow(clippy::missing_errors_doc)]

//! Build and test automation for the Swift and Kotlin bindings.

mod boltffi;
mod common;
mod gradle;
mod kotlin;
mod report;
mod swift;

use std::fmt;

use anyhow::Result;
use clap::{Parser, Subcommand, ValueEnum};

#[derive(Parser)]
#[command(name = "xtask", about = "Build automation for siegel")]
struct Cli {
    #[command(subcommand)]
    cmd: Cmd,
}

#[derive(Subcommand)]
enum Cmd {
    /// Swift bindings, packaging, and the XCTest suite.
    Swift {
        #[command(subcommand)]
        cmd: SwiftCmd,
    },
    /// Kotlin/JVM and Android bindings, packaging, and the JUnit suite.
    Kotlin {
        #[command(subcommand)]
        cmd: KotlinCmd,
    },
}

/// Which binding crate a task operates on.
#[derive(Clone, Copy, ValueEnum)]
enum Binding {
    /// `siegel-uniffi`, generated by UniFFI.
    Uniffi,
    /// `siegel-boltffi`, generated by BoltFFI.
    Boltffi,
}

impl fmt::Display for Binding {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::Uniffi => "uniffi",
            Self::Boltffi => "boltffi",
        })
    }
}

#[derive(Subcommand)]
enum SwiftCmd {
    /// Build `Siegel.xcframework` + the generated Swift sources into `swift/`.
    Build {
        #[arg(value_enum, default_value_t = Binding::Uniffi)]
        binding: Binding,
        /// Build only the simulator slice this host can load. For running the
        /// XCTest suite. Release/distribution builds must omit it.
        #[arg(long)]
        sim_only: bool,
    },
    /// Build the bindings and run the foreign XCTest suite on an iOS Simulator.
    Test {
        #[arg(value_enum, default_value_t = Binding::Uniffi)]
        binding: Binding,
    },
}

#[derive(Subcommand)]
enum KotlinCmd {
    /// Build the host cdylib + Kotlin bindings used by the JVM test suite.
    Build {
        #[arg(value_enum, default_value_t = Binding::Uniffi)]
        binding: Binding,
    },
    /// Build the host bindings and run the foreign JUnit suite on the JVM.
    Test {
        #[arg(value_enum, default_value_t = Binding::Uniffi)]
        binding: Binding,
    },
    /// Build the BoltFFI Android distribution (`jniLibs` for every ABI).
    /// Requires the Android NDK.
    Android {
        /// Extra arguments forwarded to `boltffi pack android`. Hyphenated flags
        /// pass through, so `-v` reaches boltffi rather than clap.
        #[arg(trailing_var_arg = true, allow_hyphen_values = true)]
        boltffi_args: Vec<String>,
    },
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    common::verify_project_root()?;
    match cli.cmd {
        Cmd::Swift { cmd } => match cmd {
            SwiftCmd::Build { binding, sim_only } => swift::build(binding, sim_only),
            SwiftCmd::Test { binding } => swift::test(binding),
        },
        Cmd::Kotlin { cmd } => match cmd {
            KotlinCmd::Build { binding } => kotlin::build(binding),
            KotlinCmd::Test { binding } => kotlin::test(binding),
            KotlinCmd::Android { boltffi_args } => kotlin::android(&boltffi_args),
        },
    }
}
