[package]
name = "siegel"
description = "Protected memory management for one-time use secrets."
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
name = "siegel"

[features]
# Exposes unsafe helpers for tests
test-utils = []
# Some additional intermediate logging useful for debugging
tracing = ["dep:tracing"]

[dependencies]
libc = "0.2"
thiserror = { workspace = true }
tracing = { version = "0.1", optional = true, default-features = false }
zeroize = { version = "1", features = ["derive"] }

[dev-dependencies]
sha2 = "0.10"

[lints]
workspace = true
