[package]
name = "siegel"
description = "Protected memory management for one-time use secrets."
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
name = "siegel"

[features]
# Exposes unsafe helpers for tests
test-utils = []

[dependencies]
libc = "0.2"
thiserror = { workspace = true }
zeroize = { version = "1", features = ["derive"] }

[dev-dependencies]
sha2 = "0.10"

[lints]
workspace = true
